# Generated by Django 3.2.6 on 2021-08-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
