# Generated by Django 3.2.6 on 2021-08-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210818_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_closed',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_delivery',
            field=models.DateField(blank=True),
        ),
    ]
