# Generated by Django 3.2.6 on 2021-08-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
