# Generated by Django 4.0 on 2021-12-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
