# Generated by Django 4.0 on 2021-12-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out Of Delivery', 'Out Of Delivery'), ('Delivered', 'Delivered')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
